version: '3'

services: 
  api:
    build: 
      context: .
    image: image/api-rest
    container_name: api-rest
    volumes: 
      - '.:/usr/src/app/'
    ports: 
      - 3333:3333
    command: yarn start
