version: '3'

services: 
  api:
    build: 
      context: .
    image: image/api-rest
    container_name: api-rest
    volumes: 
      - '.:/usr/src/app/'
      - /usr/src/app/node_modules/
    ports: 
      - 3333:3333
    command: yarn start
    links:
      - mongo
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge
